In [1]:
pip installstreamlit


ERROR: unknown command "installstreamlit" - maybe you meant "install"
Note: you may need to restart the kernel to use updated packages.


In [29]:
pip install --upgrade pip

Note: you may need to restart the kernel to use updated packages.


In [2]:
#Install Streamlit using pip
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression


In [3]:
#Import necessary libraries for handling data and machine learning models (e.g.,pandas, sklearn). 
from sklearn.datasets import load_iris, load_digits

# Load the IRIS dataset
iris_data = load_iris()
iris_X = iris_data.data
iris_y = iris_data.target

# Load the Digits dataset
digits_data = load_digits()
digits_X = digits_data.data
digits_y = digits_data.target


In [4]:
#Load the IRIS and Digits datasets from sklearn.datasets
import streamlit as st
from sklearn.datasets import load_iris, load_digits

# Load the IRIS dataset
iris_data = load_iris()
iris_X = iris_data.data
iris_y = iris_data.target

# Load the Digits dataset
digits_data = load_digits()
digits_X = digits_data.data
digits_y = digits_data.target

# Main function
def main():
    st.title("Dataset Selection")

    # Dataset selection
    dataset_option = st.selectbox("Select Dataset", ["IRIS", "Digits"])

    if dataset_option == "IRIS":
        st.write("Selected dataset: IRIS")
        st.write("Number of samples:", iris_X.shape[0])
        st.write("Number of features:", iris_X.shape[1])
    elif dataset_option == "Digits":
        st.write("Selected dataset: Digits")
        st.write("Number of samples:", digits_X.shape[0])
        st.write("Number of features:", digits_X.shape[1])

if __name__ == "__main__":
    main()


2024-04-24 00:53:30.805 
  command:

    streamlit run /opt/anaconda3/lib/python3.9/site-packages/ipykernel_launcher.py [ARGUMENTS]


In [5]:
from sklearn.datasets import load_iris, load_digits

# Load the IRIS dataset
iris = load_iris()
print("IRIS dataset:")
print("Features shape:", iris.data.shape)
print("Labels shape:", iris.target.shape)
print("Feature names:", iris.feature_names)
print("Target names:", iris.target_names)
print("\nFirst five rows of data:\n", iris.data[:5])

# Load the Digits dataset
digits = load_digits()
print("\nDigits dataset:")
print("Images shape:", digits.images.shape)
print("Data shape:", digits.data.shape)
print("Labels shape:", digits.target.shape)
print("\nFirst five rows of data:\n", digits.data[:5])

# You can also visualize one of the digit images:
import matplotlib.pyplot as plt

plt.gray()
plt.matshow(digits.images[0])
plt.show()

# Print the corresponding label
print("Label for the first digit image:", digits.target[0])


IRIS dataset:
Features shape: (150, 4)
Labels shape: (150,)
Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target names: ['setosa' 'versicolor' 'virginica']

First five rows of data:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

Digits dataset:
Images shape: (1797, 8, 8)
Data shape: (1797, 64)
Labels shape: (1797,)

First five rows of data:
 [[ 0.  0.  5. 13.  9.  1.  0.  0.  0.  0. 13. 15. 10. 15.  5.  0.  0.  3.
  15.  2.  0. 11.  8.  0.  0.  4. 12.  0.  0.  8.  8.  0.  0.  5.  8.  0.
   0.  9.  8.  0.  0.  4. 11.  0.  1. 12.  7.  0.  0.  2. 14.  5. 10. 12.
   0.  0.  0.  0.  6. 13. 10.  0.  0.  0.]
 [ 0.  0.  0. 12. 13.  5.  0.  0.  0.  0.  0. 11. 16.  9.  0.  0.  0.  0.
   3. 15. 16.  6.  0.  0.  0.  7. 15. 16. 16.  2.  0.  0.  0.  0.  1. 16.
  16.  3.  0.  0.  0.  0.  1. 16. 16.  6.  0.  0.  0.  0.  1. 16. 16.  6.
   0.  0.  0.  0.  0. 11. 16. 10.  0.  0.]
 [ 0.  0.  0.  4. 15. 1

/var/folders/dj/fbmx3btn19v9nh1r_91twwg40000gn/T/ipykernel_30940/3653217886.py:25: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()


In [6]:
#Provide an option for the user to select between these two datasets
from sklearn.datasets import load_iris, load_digits

def load_dataset(dataset_name):
    if dataset_name.lower() == 'iris':
        dataset = load_iris()
    elif dataset_name.lower() == 'digits':
        dataset = load_digits()
    else:
        return None, None
    
    return dataset.data, dataset.target

# User input to select the dataset
print("Please enter the dataset name (iris or digits):")
selected_dataset = input()

data, target = load_dataset(selected_dataset)

if data is not None:
    print(f"{selected_dataset.capitalize()} dataset loaded successfully.")
    print("Data shape:", data.shape)
    print("Target shape:", target.shape)
else:
    print("Invalid dataset name provided.")


Please enter the dataset name (iris or digits):
iris
Iris dataset loaded successfully.
Data shape: (150, 4)
Target shape: (150,)


In [8]:
import ipywidgets as widgets
from IPython.display import display
from sklearn.datasets import load_iris, load_digits

def load_and_display_dataset(dataset_name):
    if dataset_name == 'IRIS':
        dataset = load_iris()
    elif dataset_name == 'Digits':
        dataset = load_digits()
    else:
        print("Invalid dataset selected.")
        return
    
    print(f"{dataset_name} dataset loaded successfully.")
    print("Data shape:", dataset.data.shape)
    print("Target shape:", dataset.target.shape)

# Create a dropdown widget
dataset_selector = widgets.Dropdown(
    options=['IRIS', 'Digits'],
    value='IRIS',
    description='Dataset:',
    disabled=False,
)

# Link the dropdown to the function
interactive_widget = widgets.interactive(load_and_display_dataset, dataset_name=dataset_selector)

# Display the widget
display(interactive_widget)


interactive(children=(Dropdown(description='Dataset:', options=('IRIS', 'Digits'), value='IRIS'), Output()), _…

In [9]:
#Implement at least three machine learning classifiers (e.g., Logistic Regression,Neural Networks, Naïve Bayes
from sklearn.datasets import load_iris, load_digits
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np

# Load IRIS and Digits datasets
iris_data = load_iris()
digits_data = load_digits()

# Model options
models = {
    "Logistic Regression": LogisticRegression(),
    "Neural Networks": MLPClassifier(),
    "Naïve Bayes": GaussianNB()
}

# Function to train and evaluate the selected model
def train_and_evaluate_model(selected_model, X, y):
    model = models[selected_model]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    return accuracy

# Create a dropdown widget for model selection
from ipywidgets import interact, Dropdown

@interact(selected_model=Dropdown(options=list(models.keys())))
def select_model(selected_model):
    if selected_model:
        if selected_model == "Logistic Regression":
            X = iris_data.data
            y = iris_data.target
        elif selected_model == "Neural Networks":
            X = digits_data.data
            y = digits_data.target
        elif selected_model == "Naïve Bayes":
            X = iris_data.data
            y = iris_data.target

        accuracy = train_and_evaluate_model(selected_model, X, y)
        return f"Selected Model: {selected_model}, Accuracy: {accuracy:.2f}"

interactive(children=(Dropdown(description='selected_model', options=('Logistic Regression', 'Neural Networks'…

In [16]:
#Allow the user to select a classifier from the implemented options
import ipywidgets as widgets
from IPython.display import display
from sklearn.datasets import load_iris, load_digits
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Function to load datasets
def load_dataset(name):
    if name == 'IRIS':
        return load_iris()
    elif name == 'Digits':
        return load_digits()

# Function to select a classifier
def select_classifier(name):
    if name == 'Logistic Regression':
        return LogisticRegression(max_iter=200)
    elif name == 'Decision Tree':
        return DecisionTreeClassifier()
    elif name == 'KNN':
        return KNeighborsClassifier()

# Function to create input fields based on dataset features
def create_feature_inputs(features):
    inputs = []
    for feature in features:
        input_box = widgets.FloatText(
            value=0.0,
            description=feature,
            disabled=False,
            style={'description_width': 'initial'}
        )
        inputs.append(input_box)
    return inputs

# Function to handle dataset selection
def on_dataset_change(change):
    if change['type'] == 'change' and change['name'] == 'value':
        dataset = load_dataset(change['new'])
        feature_inputs.children = create_feature_inputs(dataset.feature_names)

# Function to predict using inputs
def on_predict_button_clicked(b):
    dataset = load_dataset(dataset_selector.value)
    classifier = select_classifier(classifier_selector.value)
    model = classifier.fit(dataset.data, dataset.target)
    
    input_values = [input.value for input in feature_inputs.children]
    prediction = model.predict([input_values])
    print(f"Predicted class: {dataset.target_names[prediction][0]}")

# Dropdown selectors
dataset_selector = widgets.Dropdown(
    options=['IRIS', 'Digits'],
    description='Dataset:',
)

classifier_selector = widgets.Dropdown(
    options=['Logistic Regression', 'Nueral networks', 'Naïve Bayes'],
    description='Classifier:',
)

dataset_selector.observe(on_dataset_change)

# Button to make a prediction
predict_button = widgets.Button(description="Predict")
predict_button.on_click(on_predict_button_clicked)

# Box to hold input fields for feature values
feature_inputs = widgets.VBox([])
on_dataset_change({'type': 'change', 'name': 'value', 'new': 'IRIS'})

# Display widgets
display(widgets.VBox([dataset_selector, classifier_selector, feature_inputs, predict_button]))


Predicted class: virginica
Predicted class: virginica


In [11]:
#Based on the selected dataset, dynamically generate input fields for the user to
#enter feature values. Ensure that input fields are appropriately labeled.
import pandas as pd
from sklearn.datasets import load_iris, load_digits
from ipywidgets import interact, FloatText, IntText

# Load IRIS and Digits datasets
iris_data = load_iris()
digits_data = load_digits()

# Function to dynamically generate input fields based on selected dataset
def generate_input_fields(selected_dataset):
    if selected_dataset == "IRIS":
        feature_names = iris_data.feature_names
        input_widgets = [FloatText(description=name) for name in feature_names]
    elif selected_dataset == "Digits":
        feature_names = [f"Feature {i}" for i in range(digits_data.data.shape[1])]
        input_widgets = [IntText(description=name) for name in feature_names]
    else:
        return "Invalid dataset selection"
    return input_widgets

# Create a dropdown widget for dataset selection
@interact(selected_dataset=["IRIS", "Digits"])
def select_dataset(selected_dataset):
    return generate_input_fields(selected_dataset)

interactive(children=(Dropdown(description='selected_dataset', options=('IRIS', 'Digits'), value='IRIS'), Outp…

In [12]:
import pandas as pd
from sklearn.datasets import load_iris, load_digits
from ipywidgets import interact, FloatText, IntText

# Load IRIS and Digits datasets
iris_data = load_iris()
digits_data = load_digits()

# Function to dynamically generate input fields based on selected dataset
def generate_input_fields(selected_dataset):
    if selected_dataset == "IRIS":
        feature_names = iris_data.feature_names
        input_widgets = [FloatText(description=name) for name in feature_names]
    elif selected_dataset == "Digits":
        feature_names = [f"Feature {i}" for i in range(digits_data.data.shape[1])]
        input_widgets = [IntText(description=name) for name in feature_names]
    else:
        return "Invalid dataset selection"
    return input_widgets

# Create a dropdown widget for dataset selection
@interact(selected_dataset=["IRIS", "Digits"])
def select_dataset(selected_dataset):
    return generate_input_fields(selected_dataset)

interactive(children=(Dropdown(description='selected_dataset', options=('IRIS', 'Digits'), value='IRIS'), Outp…

In [14]:
#Once the user selects the dataset, classifier, and inputs all necessary featurevalues, provide a button to make predictions
#Display the prediction result to the user in a clear and understandable manner
import pandas as pd
from sklearn.datasets import load_iris, load_digits
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.naive_bayes import GaussianNB
from ipywidgets import interact, Dropdown, FloatText, IntText, Button, Output

# Load IRIS and Digits datasets
iris_data = load_iris()
digits_data = load_digits()

# Model options
models = {
    "Logistic Regression": LogisticRegression(),
    "Neural Networks": MLPClassifier(),
    "Naïve Bayes": GaussianNB()
}

# Function to make predictions based on selected dataset, model, and input values
def make_prediction(selected_dataset, selected_model, **kwargs):
    if selected_dataset == "IRIS":
        X = pd.DataFrame([list(kwargs.values())], columns=iris_data.feature_names)
        model = models[selected_model]
        model.fit(iris_data.data, iris_data.target)
        prediction = model.predict(X)
        return f"Prediction: {iris_data.target_names[prediction][0]}"
    elif selected_dataset == "Digits":
        X = pd.DataFrame([list(kwargs.values())])
        model = models[selected_model]
        model.fit(digits_data.data, digits_data.target)
        prediction = model.predict(X)
        return f"Prediction: {prediction[0]}"
    else:
        return "Invalid dataset selection"

# Create input widgets for dataset, model, and feature values
dataset_widget = Dropdown(options=["IRIS", "Digits"], description="Dataset")
model_widget = Dropdown(options=list(models.keys()), description="Model")

feature_widgets = {}
for feature_name in iris_data.feature_names:
    feature_widgets[feature_name] = FloatText(description=feature_name)

button = Button(description="Make Prediction")
output = Output()

# Function to handle button click event
def on_button_click(b):
    with output:
        output.clear_output()
        dataset = dataset_widget.value
        model = model_widget.value
        feature_values = {name: widget.value for name, widget in feature_widgets.items()}
        prediction = make_prediction(dataset, model, **feature_values)
        print(prediction)

# Attach button click event handler
button.on_click(on_button_click)

# Display widgets and output
display(dataset_widget)
display(model_widget)
for widget in feature_widgets.values():
    display(widget)
display(button)
display(output)

Dropdown(description='Dataset', options=('IRIS', 'Digits'), value='IRIS')

Dropdown(description='Model', options=('Logistic Regression', 'Neural Networks', 'Naïve Bayes'), value='Logist…

FloatText(value=0.0, description='sepal length (cm)')

FloatText(value=0.0, description='sepal width (cm)')

FloatText(value=0.0, description='petal length (cm)')

FloatText(value=0.0, description='petal width (cm)')

Button(description='Make Prediction', style=ButtonStyle())

Output()

In [15]:
#Ensure the application is user-friendly and intuitive.
#Organize the layout such that the data selection, model selection, input fields,and prediction results are logically structured
import pandas as pd
from sklearn.datasets import load_iris, load_digits
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.naive_bayes import GaussianNB
from ipywidgets import interact, Dropdown, FloatText, IntText, Button, Output, VBox, HBox

# Load IRIS and Digits datasets
iris_data = load_iris()
digits_data = load_digits()

# Model options
models = {
    "Logistic Regression": LogisticRegression(),
    "Neural Networks": MLPClassifier(),
    "Naïve Bayes": GaussianNB()
}

# Function to make predictions based on selected dataset, model, and input values
def make_prediction(selected_dataset, selected_model, **kwargs):
    if selected_dataset == "IRIS":
        X = pd.DataFrame([list(kwargs.values())], columns=iris_data.feature_names)
        model = models[selected_model]
        model.fit(iris_data.data, iris_data.target)
        prediction = model.predict(X)
        return f"Prediction: {iris_data.target_names[prediction][0]}"
    elif selected_dataset == "Digits":
        X = pd.DataFrame([list(kwargs.values())])
        model = models[selected_model]
        model.fit(digits_data.data, digits_data.target)
        prediction = model.predict(X)
        return f"Prediction: {prediction[0]}"
    else:
        return "Invalid dataset selection"

# Create input widgets for dataset, model, and feature values
dataset_widget = Dropdown(options=["IRIS", "Digits"], description="Dataset")
model_widget = Dropdown(options=list(models.keys()), description="Model")

feature_widgets = {}
for feature_name in iris_data.feature_names:
    feature_widgets[feature_name] = FloatText(description=feature_name)

button = Button(description="Make Prediction")
output = Output()

# Function to handle button click event
def on_button_click(b):
    with output:
        output.clear_output()
        dataset = dataset_widget.value
        model = model_widget.value
        feature_values = {name: widget.value for name, widget in feature_widgets.items()}
        prediction = make_prediction(dataset, model, **feature_values)
        print(prediction)

# Attach button click event handler
button.on_click(on_button_click)

# Organize the layout using VBox and HBox
data_selection_box = VBox([dataset_widget, model_widget])
feature_inputs_box = VBox(list(feature_widgets.values()))
input_box = HBox([data_selection_box, feature_inputs_box])
prediction_box = VBox([button, output])

# Display the user interface
display(input_box, prediction_box)
